default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db

development:
  <<: *default
  database: <%=ENV["DATABASE_URL"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  user: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

test:
  <<: *default
  database: <%=ENV["DATABASE_URL"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  user: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
